server:
  port: 8000

spring:
  main:
    banner-mode: "off"

  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      base-path: "/"
  endpoint:
    health:
      probes:
        enabled: true